app/bp_geo/models/__init__.py
from flask import url_for
from mongoengine import QuerySet

from ext import db, bcrypt


class FeatureQuerySet(QuerySet):
    """Extends QuerySet by a to_collection method"""
    def to_collection(self):
        data = {
            'type': 'FeatureCollection',
            'features': [f.to_feature() for f in self]
        }
        return data


class Feature(db.Document):
    """A Point Feature

    valid Feature:
    - geometry: type: "Point", coordinates: <two-dim Array>
    - type: "Feature"
    - properties: a dict

    """

    type = db.StringField(default='Feature', choices=['Feature'])
    geometry = db.PointField(null=False)
    properties = db.DictField()

    meta = {
        'allow_inheritance': True,
        'abstract': True,
        'queryset_class': FeatureQuerySet
    }

    def to_feature(self):
        data = {
            'id': str(self.id),
            'type': self.type,
            'geometry': self.geometry,
            'properties': self.properties,
            'timestamp': str(self.id.generation_time),
            'uri': url_for('api.get_item', collection=self.slug, item_id=self.id, _external=True)
        }
        return data

    def from_dict(self, data):
        self.geometry = data.get('geometry')
        self.properties = data.get('properties')


class Arena(Feature):
    slug = 'arenas'


class Match(Feature):
    slug = 'matches'


class Admin(db.Document):
    _pwd = db.StringField(db_field='pwd')

    @property
    def pwd(self):
        return self._pwd

    @pwd.setter
    def pwd(self, value):
        try:
            self._pwd = bcrypt.generate_password_hash(value.encode('utf-8'))
        except (ValueError, AttributeError):
            raise ValueError('Cant set password. Probably empty value')

    def auth(self, plaintext):
        try:
            return bcrypt.check_password_hash(self._pwd.encode('utf-8'), plaintext.encode('utf-8'))
        except (ValueError, AttributeError, KeyError):
            return False

app/bp_geo/__init__.py
from flask import Flask
from models import db, bcrypt
from routes import api, admin, login

from config import init_config
from url_converter import ObjectIDConverter
from errorhandler import init_errorhandler


def register_blueprints(app):
    # app.register_blueprint(login)
    app.register_blueprint(api, url_prefix='/features')
    # app.register_blueprint(admin)


def create_app(**config):
    app = Flask(__name__)

    app.url_map.converters['objectid'] = ObjectIDConverter
    init_errorhandler(app)

    init_config(app)
    app.config.from_mapping(config)

    db.init_app(app)
    bcrypt.init_app(app)

    register_blueprints(app)



    return app

app/bp_geo/models/ext/__init__.py
from flask_mongoengine import MongoEngine
from flask_bcrypt import Bcrypt

db = MongoEngine()
bcrypt = Bcrypt()

app/bp_geo/routes/__init__.py
from api import api
from admin import admin
from login import login

app/bp_geo/routes/admin.py
from flask import Blueprint, render_template

admin = Blueprint('admin', __name__)


@admin.route('/admin')
def index():
    return render_template('admin/index.html')

app/bp_geo/routes/api.py
from flask import Blueprint, request, jsonify, abort, g
from mongoengine import ValidationError
from app.bp_geo.models import Arena, Match

api = Blueprint('api', __name__)


# ----------------------------------------------------------------------------------------------------------------------
# URL Preprocessor
# ----------------------------------------------------------------------------------------------------------------------

@api.url_value_preprocessor
def preprocessor(endpoint, values):
    """parses url values to g object

    g.collection = collection class
    g.item = specific item

    can result in 404
    """

    collection = values.pop('collection', None)

    if collection == 'arenas':
        g.collection = Arena
    elif collection == 'matches':
        g.collection = Match
    else:
        abort(404)

    item_id = values.pop('item_id', None)
    if not item_id:
        return

    g.item = g.collection.objects(id=item_id).first()
    if not g.item:
        abort(404)

    return


# ----------------------------------------------------------------------------------------------------------------------
# Routes whole collection
# ----------------------------------------------------------------------------------------------------------------------

@api.route('/<collection>', methods=['POST'])
def post_collection():
    data = request.get_json(force=True)

    feature = g.collection()
    feature.from_dict(data)

    try:
        feature.save()
    except ValidationError as e:
        return abort(400, 'Valid JSON, but could not save as feature')

    resp = jsonify(feature.to_feature())
    resp.headers['Location'] = feature.to_feature().get('uri', None)

    return resp


@api.route('/<collection>', methods=['GET'])
def get_collection():
    return jsonify(g.collection.objects().to_collection())


# ----------------------------------------------------------------------------------------------------------------------
# Routes: single item
# ----------------------------------------------------------------------------------------------------------------------

@api.route('/<collection>/<objectid:item_id>', methods=['GET'])
def get_item():
    return jsonify(g.item.to_feature())


@api.route('/<collection>/<objectid:item_id>', methods=['PUT'])
def put_item():
    data = request.get_json(force=True)

    g.item.from_dict(data)

    try:
        g.item.save()
    except ValidationError as e:
        return abort(400, 'Valid JSON, but could not save as feature')

    return jsonify(g.item.to_feature())


@api.route('/<collection>/<objectid:item_id>', methods=['DELETE'])
def delete_item():
    g.item.delete()

    return jsonify({'response': 'Feature sucessfully deleted', 'feature': g.item.to_feature()})

app/bp_geo/routes/login.py
from flask import Blueprint, render_template, request, abort, session, redirect, url_for
from app.bp_geo.models import Admin

login = Blueprint('login', __name__)


@login.route('/', methods=['GET', 'POST'])
def index():
    if session.get('logged_in'):
        return redirect(url_for('admin.index'))

    admin = Admin.objects().first()

    if request.method == 'POST':
        if not admin:
            return abort('there is no admin account')

        pwd = request.form.get('pwd')

        if not admin.auth(pwd):
            return abort('password not match')

        session['logged_in'] = True
        return redirect(url_for('admin.index'))

    return render_template('login/login.html', admin=admin)


@login.route('/create', methods=['POST'])
def create():
    admin = Admin.objects().first()

    if admin:
        return abort('there is already an admin account')

    pwd = request.form.get('pwd')

    if not pwd or len(pwd) < 3:
        return abort('password not in data or too short (min: 3)')

    admin = Admin()
    admin.pwd = pwd
    admin.save()

    session['logged_in'] = True
    return redirect(url_for('login.index'))


@login.route('/logout')
def logout():
    session['logged_in'] = False
    return redirect(url_for('login.index'))

app/bp_geo/templates/admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BP-Geo Admin</title>

    <link rel="stylesheet" href="{{ url_for('static', filename='leaflet/leaflet.css') }}" />
    <script src="{{ url_for('static', filename='leaflet/leaflet.js') }}"></script>

    <script src="{{ url_for('static', filename='jquery-3.2.1.min.js') }}"></script>

    <style>
        #mapid { height: 300px; }
    </style>
</head>
<body>
    <h1>BP-Geo Admin</h1>
    <div id="mapid"></div>

    <button onclick="clear()">Clear</button>

    <script>
        var mymap = L.map('mapid').setView([0, 0], 2);

        L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
            attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
            maxZoom: 18,
            id: 'mapbox.streets',
            accessToken: 'pk.eyJ1IjoiZmlzY2hlcmZyZWRsIiwiYSI6ImNqM2NwbmdoOTAwMzAydnMxc29sMGdjYzYifQ.CJ1WD4zM_ArZkXwMuzTytQ'
        }).addTo(mymap);

        var myLayer = L.geoJSON().addTo(mymap);

    </script>

    <script>
        function addFeature(x, y) {
            var f;

            x = x ||Math.random() * 360 - 180;
            y = y || Math.random() * 140 - 70;

            f = {
                "geometry": {"type": "Point", "coordinates": [x, y]},
                "properties": {"hello": "fuck", "yaay": "whoo", "name": "Peter"},
                "type": "Feature"
            };

            $.ajax({
                url: "/arena",
                type: "POST",
                contentType: "application/json",
                dataType: "json",
                data: JSON.stringify(f)
            });
        }

        for(var i = 0; i < 50; i++) {
            addFeature()
        }

        $.getJSON("/arena", function(data) {
            console.log(data)
            myLayer.addData(data)
        });

        console.log(myLayer);

        function clear() {
            console.log("test");
            myLayer.clear();
        }


    </script>


</body>
</html>

app/bp_geo/templates/login/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BP-Geo Login</title>
</head>
<body>
    <h1>BP-Geo Admin interface</h1>

    {% if admin %}
        <p>Please login</p>
    {% else %}
        <p>There is currently no admin account registered. Please create one.</p>
    {% endif %}

    <form action="{% if admin %}{{ url_for('login.index') }}{% else %}{{ url_for('login.create') }}{% endif %}" method="post">
        <label><b>Password: </b></label><input type="password" name="pwd">
        <input type="submit" value="Submit">

    </form>

</body>
</html>